GET http://localhost:3000/data

###

GET http://localhost:3000/data/

###

POST http://localhost:3000/data

Content-Type: application/json
{
    "Title": "test",
    "image": "image path",
    "Desc": "blah blah this should work",
    "difficulty": "harder than diamond",
    "units": "106",
    "data": [{"exercise": "beleh", "torc": "20s"},{"exercise": "beleh2", "torc": "204s"}]
}

